# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cd84ed8bc1c207b12fa544ead86f01f9e88f57f7709c2cde761429d875424d34dfb8288fffbbe9f9aeb0112da9dd051f2207a1f8477e985e6f02dd16a267642

test:
  secret_key_base: 129deea7b740cbcd8b98674b74cc8e58da1f7232f0b9511c4bc63d913d26c24955dd02d649b1afb214b64168e9d0b9ad238954d000f27f96a1b01ec7c3677a7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
